/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import paquete.Comentario;
import paquete.Pelicula;
import paquete.SesionActiva;

/**
 *
 * @author Alexa
 */
public class CalificacionPelis extends javax.swing.JFrame {

    private Pelicula peliculaActual;

    /**
     * Creates new form CalificacionPelis
     */
    public CalificacionPelis(Pelicula pelicula) {
        this.peliculaActual = pelicula;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbPuntuacion = new javax.swing.JComboBox<>();
        txtSubtituloPuntuacion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaComentario = new javax.swing.JTextArea();
        txtSubtituloComentario = new javax.swing.JLabel();
        txtTituloCalificacion = new javax.swing.JLabel();
        btn_guardarCalificacion = new javax.swing.JButton();
        btn_cancelarCalificacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(57, 62, 70));

        cmbPuntuacion.setForeground(new java.awt.Color(255, 255, 51));
        cmbPuntuacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "★★★★★", "★★★★☆", "★★★☆☆", "★★☆☆☆", "★☆☆☆☆" }));
        cmbPuntuacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPuntuacionActionPerformed(evt);
            }
        });

        txtSubtituloPuntuacion.setBackground(new java.awt.Color(255, 255, 255));
        txtSubtituloPuntuacion.setForeground(new java.awt.Color(255, 255, 255));
        txtSubtituloPuntuacion.setText("Puntuación:");

        txtAreaComentario.setColumns(20);
        txtAreaComentario.setRows(5);
        jScrollPane1.setViewportView(txtAreaComentario);

        txtSubtituloComentario.setBackground(new java.awt.Color(255, 255, 255));
        txtSubtituloComentario.setForeground(new java.awt.Color(255, 255, 255));
        txtSubtituloComentario.setText("Comentarios:");

        txtTituloCalificacion.setBackground(new java.awt.Color(255, 255, 255));
        txtTituloCalificacion.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtTituloCalificacion.setForeground(new java.awt.Color(255, 255, 255));
        txtTituloCalificacion.setText("Califica la película");

        btn_guardarCalificacion.setBackground(new java.awt.Color(144, 55, 73));
        btn_guardarCalificacion.setForeground(new java.awt.Color(255, 255, 255));
        btn_guardarCalificacion.setText("Guardar");
        btn_guardarCalificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarCalificacionActionPerformed(evt);
            }
        });

        btn_cancelarCalificacion.setBackground(new java.awt.Color(144, 55, 73));
        btn_cancelarCalificacion.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancelarCalificacion.setText("Cancelar");
        btn_cancelarCalificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarCalificacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPuntuacion, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSubtituloComentario, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTituloCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSubtituloPuntuacion, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_guardarCalificacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_cancelarCalificacion)
                .addGap(80, 80, 80))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(txtTituloCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSubtituloPuntuacion)
                .addGap(18, 18, 18)
                .addComponent(cmbPuntuacion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtSubtituloComentario)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guardarCalificacion)
                    .addComponent(btn_cancelarCalificacion))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarCalificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarCalificacionActionPerformed
        int puntuacion = 5 - cmbPuntuacion.getSelectedIndex();
        Comentario cmtr = new Comentario(SesionActiva.getPersona().getNombre(), puntuacion, txtAreaComentario.getText());
        this.peliculaActual.addComentario(cmtr);
        actualizarPeli();
        JOptionPane.showMessageDialog(null, "El comentario ha sido agregado con éxito.");
        this.dispose();
    }//GEN-LAST:event_btn_guardarCalificacionActionPerformed

    private void actualizarPeli() {
        ArrayList<Pelicula> peliculas = null;

        try {
            try (FileInputStream archivoPeliculaInput = new FileInputStream("Peliculas.alexa")) {
                ObjectInputStream input = new ObjectInputStream(archivoPeliculaInput);

                peliculas = (ArrayList<Pelicula>) input.readObject();

                input.close();
            }
        } catch (Exception ex) {
            System.out.println("Exception: " + ex.getMessage());
        }

        if (peliculas == null) {
            peliculas = new ArrayList<>();
        }
        for(Pelicula pelicula : peliculas) {
            if(pelicula.getNombre().equals(peliculaActual.getNombre())) {
                pelicula.setComentarios(peliculaActual.getComentario());
            }
        }

        try {
            try (FileOutputStream archivoPelicula = new FileOutputStream("Peliculas.alexa")) {
                ObjectOutputStream output = new ObjectOutputStream(archivoPelicula);

                output.writeObject(peliculas);

                output.close();

            }

            JOptionPane.showMessageDialog(null, "La pelicula ha sido agregada ala categoría indicada.");

        } catch (Exception ex) {
            System.out.println("Exception: " + ex.getMessage());
        }
        this.dispose();
    }
    
    private void btn_cancelarCalificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarCalificacionActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cancelarCalificacionActionPerformed

    private void cmbPuntuacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPuntuacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPuntuacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalificacionPelis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalificacionPelis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalificacionPelis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalificacionPelis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalificacionPelis(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelarCalificacion;
    private javax.swing.JButton btn_guardarCalificacion;
    private javax.swing.JComboBox<String> cmbPuntuacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaComentario;
    private javax.swing.JLabel txtSubtituloComentario;
    private javax.swing.JLabel txtSubtituloPuntuacion;
    private javax.swing.JLabel txtTituloCalificacion;
    // End of variables declaration//GEN-END:variables
}
