/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.TreeSet;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import paquete.Categoria;
import paquete.Comentario;
import paquete.Pelicula;
import paquete.SesionActiva;

/**
 *
 * @author Alexa
 */
public class EliminarPelicula extends javax.swing.JFrame {

    private String nombrePeliculaSeleccionada = "";

    /**
     * Creates new form CalificacionPelis
     */
    public EliminarPelicula() {
        initComponents();

        listResultadosObtenidosPeliculas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        listResultadosObtenidosPeliculas.removeAll();

        listResultadosObtenidosPeliculas.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                int indicePeliculaSeleccionada = e.getFirstIndex();
                ListModel<String> itemsLista = listResultadosObtenidosPeliculas.getModel();
                nombrePeliculaSeleccionada = itemsLista.getElementAt(indicePeliculaSeleccionada);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblPeliculaBuscada = new javax.swing.JLabel();
        lblResultadosObtenidosPeliculas = new javax.swing.JLabel();
        txtBusquedaPeliculaEliminar = new javax.swing.JLabel();
        btn_EliminarPelicula = new javax.swing.JButton();
        btn_cancelarCalificacion = new javax.swing.JButton();
        txtPeliculaBuscada = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        listResultadosObtenidosPeliculas = new javax.swing.JList<>();
        btnBuscarPelicula = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(57, 62, 70));

        lblPeliculaBuscada.setBackground(new java.awt.Color(255, 255, 255));
        lblPeliculaBuscada.setForeground(new java.awt.Color(255, 255, 255));
        lblPeliculaBuscada.setText("Nombre:");

        lblResultadosObtenidosPeliculas.setBackground(new java.awt.Color(255, 255, 255));
        lblResultadosObtenidosPeliculas.setForeground(new java.awt.Color(255, 255, 255));
        lblResultadosObtenidosPeliculas.setText("Resultados Obtenidos:");

        txtBusquedaPeliculaEliminar.setBackground(new java.awt.Color(255, 255, 255));
        txtBusquedaPeliculaEliminar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtBusquedaPeliculaEliminar.setForeground(new java.awt.Color(255, 255, 255));
        txtBusquedaPeliculaEliminar.setText("Buscar Película");

        btn_EliminarPelicula.setBackground(new java.awt.Color(144, 55, 73));
        btn_EliminarPelicula.setForeground(new java.awt.Color(255, 255, 255));
        btn_EliminarPelicula.setText("Eliminar");
        btn_EliminarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarPeliculaActionPerformed(evt);
            }
        });

        btn_cancelarCalificacion.setBackground(new java.awt.Color(144, 55, 73));
        btn_cancelarCalificacion.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancelarCalificacion.setText("Cancelar");
        btn_cancelarCalificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarCalificacionActionPerformed(evt);
            }
        });

        txtPeliculaBuscada.setBackground(new java.awt.Color(255, 255, 255));

        listResultadosObtenidosPeliculas.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(listResultadosObtenidosPeliculas);

        btnBuscarPelicula.setBackground(new java.awt.Color(144, 55, 73));
        btnBuscarPelicula.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarPelicula.setText("Buscar");
        btnBuscarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPeliculaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_EliminarPelicula)
                .addGap(18, 18, 18)
                .addComponent(btn_cancelarCalificacion)
                .addGap(54, 54, 54))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtPeliculaBuscada, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarPelicula))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBusquedaPeliculaEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPeliculaBuscada, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblResultadosObtenidosPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(txtBusquedaPeliculaEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPeliculaBuscada)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPeliculaBuscada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPelicula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(lblResultadosObtenidosPeliculas)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_EliminarPelicula)
                    .addComponent(btn_cancelarCalificacion))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_EliminarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarPeliculaActionPerformed

        ArrayList<Pelicula> peliculas = null;

        try {
            try (FileInputStream archivoPeliculaInput = new FileInputStream("Peliculas.alexa")) {
                ObjectInputStream input = new ObjectInputStream(archivoPeliculaInput);

                peliculas = (ArrayList<Pelicula>) input.readObject();

                input.close();
            }
        } catch (Exception ex) {
            System.out.println("Exception: " + ex.getMessage());
        }

        if (peliculas == null) {
            peliculas = new ArrayList<>();
        }
        
        int indexPeliculaEliminar = -1;
        for(Pelicula pelicula : peliculas) {
            if(pelicula.getNombre().equals(nombrePeliculaSeleccionada)) {
                indexPeliculaEliminar = peliculas.indexOf(pelicula);
            }
        }
        peliculas.remove(indexPeliculaEliminar);

        try {
            try (FileOutputStream archivoPelicula = new FileOutputStream("Peliculas.alexa")) {
                ObjectOutputStream output = new ObjectOutputStream(archivoPelicula);

                output.writeObject(peliculas);

                output.close();

            }

            JOptionPane.showMessageDialog(null, "La pelicula ha sido eliminada satisfactoriamente.");

        } catch (Exception ex) {
            System.out.println("Exception: " + ex.getMessage());
        }
        this.dispose();
    }//GEN-LAST:event_btn_EliminarPeliculaActionPerformed

    private ArrayList<Pelicula> getPeliculas() {
        ArrayList<Pelicula> peliculas = null;

        try {
            try (FileInputStream archivoPeliculaInput = new FileInputStream("Peliculas.alexa")) {
                ObjectInputStream input = new ObjectInputStream(archivoPeliculaInput);

                peliculas = (ArrayList<Pelicula>) input.readObject();

                input.close();
            }
        } catch (Exception ex) {
            System.out.println("Exception: " + ex.getMessage());
        }

        return peliculas;
    }

    private void btn_cancelarCalificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarCalificacionActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cancelarCalificacionActionPerformed

    private void btnBuscarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPeliculaActionPerformed
        ArrayList<Pelicula> peliculas = getPeliculas();
        ArrayList<String> nombrePeliculas = new ArrayList<>();

        for (Pelicula pelicula : peliculas) {
            if (pelicula.getNombre().toLowerCase().contains(txtPeliculaBuscada.getText().toLowerCase())) {
                nombrePeliculas.add(pelicula.getNombre());
            }
        }

        DefaultListModel model = new DefaultListModel();
        model.addAll(nombrePeliculas);
        listResultadosObtenidosPeliculas.setModel(model);
    }//GEN-LAST:event_btnBuscarPeliculaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliminarPelicula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPelicula;
    private javax.swing.JButton btn_EliminarPelicula;
    private javax.swing.JButton btn_cancelarCalificacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblPeliculaBuscada;
    private javax.swing.JLabel lblResultadosObtenidosPeliculas;
    private javax.swing.JList<String> listResultadosObtenidosPeliculas;
    private javax.swing.JLabel txtBusquedaPeliculaEliminar;
    private javax.swing.JTextField txtPeliculaBuscada;
    // End of variables declaration//GEN-END:variables
}
