/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import paquete.Comentario;
import paquete.Pelicula;

/**
 *
 * @author Usuario
 */
public class InfoPelis extends javax.swing.JFrame {

    private Pelicula peliculaActual;

    /**
     * Creates new form InfoPelis
     */
    public InfoPelis(Pelicula peliculaActual) {
        this.peliculaActual = peliculaActual;
        initComponents();

        lblTituloPelicula.setText(peliculaActual.getNombre());
        lblCategoriaPelicula.setText(peliculaActual.getCategoria().name());
        lblLenguajePelicula.setText(peliculaActual.getLenguaje());
        lblDescripcionPelicula.setText(peliculaActual.getDescripcion());

        int calificacion = 0;
        ArrayList<Comentario> comentarios = peliculaActual.getComentario();
        if (comentarios.size() > 0) {
            for (Comentario comentario : comentarios) {
                calificacion += comentario.getCalificacion();
            }
            calificacion = calificacion / comentarios.size();
        }

        switch (calificacion) {
            case 5:
                lblCalificacionPelicula.setText("★★★★★");
                break;
            case 4:
                lblCalificacionPelicula.setText("★★★★☆");
                break;
            case 3:
                lblCalificacionPelicula.setText("★★★☆☆");
                break;
            case 2:
                lblCalificacionPelicula.setText("★★☆☆☆");
                break;
            case 1:
                lblCalificacionPelicula.setText("★☆☆☆☆");
                break;
            default:
                lblCalificacionPelicula.setText("★★★★★");
                break;
        }
        
        ImageIcon icon = new ImageIcon(getClass().getResource(peliculaActual.getUrlImagen()));
            Image image = icon.getImage();
            // Se le hace resize a la imagen
            Image scaledImage = image.getScaledInstance(186, 370, java.awt.Image.SCALE_SMOOTH);
            icon = new ImageIcon(scaledImage);
            fotoPeli.setIcon(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_calificar = new javax.swing.JButton();
        OkButton = new javax.swing.JButton();
        lblComentarios = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        lblLenguaje = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblTituloPelicula = new javax.swing.JLabel();
        lblCategoriaPelicula = new javax.swing.JLabel();
        lblLenguajePelicula = new javax.swing.JLabel();
        lblDescripcionPelicula = new javax.swing.JLabel();
        lblCalificacionPelicula = new javax.swing.JLabel();
        btnComentarios = new javax.swing.JButton();
        fotoPeli = new javax.swing.JButton();

        Titulo2.setText("Duracion");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(57, 62, 70));

        jPanel1.setBackground(new java.awt.Color(57, 62, 70));

        btn_calificar.setBackground(new java.awt.Color(144, 55, 73));
        btn_calificar.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        btn_calificar.setForeground(new java.awt.Color(255, 255, 255));
        btn_calificar.setText("Calificar");
        btn_calificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calificarActionPerformed(evt);
            }
        });

        OkButton.setBackground(new java.awt.Color(144, 55, 73));
        OkButton.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        OkButton.setForeground(new java.awt.Color(255, 255, 255));
        OkButton.setText("Volver");
        OkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkButtonActionPerformed(evt);
            }
        });

        lblComentarios.setBackground(new java.awt.Color(255, 255, 255));
        lblComentarios.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        lblComentarios.setForeground(new java.awt.Color(255, 255, 255));
        lblComentarios.setText("Calificación Promedio");

        lblDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        lblDescripcion.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        lblDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        lblDescripcion.setText("Descripción");

        lblLenguaje.setBackground(new java.awt.Color(255, 255, 255));
        lblLenguaje.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        lblLenguaje.setForeground(new java.awt.Color(255, 255, 255));
        lblLenguaje.setText("Lenguaje");

        lblCategoria.setBackground(new java.awt.Color(255, 255, 255));
        lblCategoria.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        lblCategoria.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoria.setText("Categoría");

        lblTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lblTitulo.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Titulo");

        lblTituloPelicula.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloPelicula.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        lblTituloPelicula.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloPelicula.setText("jLabel1");

        lblCategoriaPelicula.setBackground(new java.awt.Color(255, 255, 255));
        lblCategoriaPelicula.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        lblCategoriaPelicula.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoriaPelicula.setText("jLabel1");

        lblLenguajePelicula.setBackground(new java.awt.Color(255, 255, 255));
        lblLenguajePelicula.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        lblLenguajePelicula.setForeground(new java.awt.Color(255, 255, 255));
        lblLenguajePelicula.setText("jLabel1");

        lblDescripcionPelicula.setBackground(new java.awt.Color(255, 255, 255));
        lblDescripcionPelicula.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        lblDescripcionPelicula.setForeground(new java.awt.Color(255, 255, 255));
        lblDescripcionPelicula.setText("jLabel1");

        lblCalificacionPelicula.setBackground(new java.awt.Color(255, 255, 255));
        lblCalificacionPelicula.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblCalificacionPelicula.setForeground(new java.awt.Color(255, 255, 255));
        lblCalificacionPelicula.setText("jLabel1");

        btnComentarios.setBackground(new java.awt.Color(87, 86, 86));
        btnComentarios.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        btnComentarios.setForeground(new java.awt.Color(255, 255, 255));
        btnComentarios.setText("Ver Comentarios");
        btnComentarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComentariosActionPerformed(evt);
            }
        });

        fotoPeli.setBackground(new java.awt.Color(57, 62, 70));
        fotoPeli.setForeground(java.awt.Color.darkGray);
        fotoPeli.setText("jButton1");
        fotoPeli.setBorder(null);
        fotoPeli.setBorderPainted(false);
        fotoPeli.setFocusPainted(false);
        fotoPeli.setFocusable(false);
        fotoPeli.setMargin(new java.awt.Insets(0, 0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fotoPeli, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnComentarios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(OkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblDescripcionPelicula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblComentarios, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLenguaje, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCalificacionPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLenguajePelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCategoriaPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTituloPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_calificar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(fotoPeli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTitulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTituloPelicula))
                            .addComponent(btn_calificar))
                        .addGap(12, 12, 12)
                        .addComponent(lblCategoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCategoriaPelicula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblLenguaje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLenguajePelicula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDescripcion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDescripcionPelicula, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblComentarios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCalificacionPelicula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnComentarios)
                            .addComponent(OkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComentariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComentariosActionPerformed
        Comentarios test = new Comentarios(peliculaActual);
        test.setVisible(true);
    }//GEN-LAST:event_btnComentariosActionPerformed

    private void OkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_OkButtonActionPerformed

    private void btn_calificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calificarActionPerformed
        CalificacionPelis cal = new CalificacionPelis(peliculaActual);
        cal.setVisible(true);
    }//GEN-LAST:event_btn_calificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoPelis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoPelis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoPelis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoPelis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfoPelis(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OkButton;
    private javax.swing.JLabel Titulo2;
    private javax.swing.JButton btnComentarios;
    private javax.swing.JButton btn_calificar;
    private javax.swing.JButton fotoPeli;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCalificacionPelicula;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblCategoriaPelicula;
    private javax.swing.JLabel lblComentarios;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblDescripcionPelicula;
    private javax.swing.JLabel lblLenguaje;
    private javax.swing.JLabel lblLenguajePelicula;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloPelicula;
    // End of variables declaration//GEN-END:variables
}
