/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.util.ArrayList;
import paquete.Comentario;
import paquete.Pelicula;

/**
 *
 * @author Usuario
 */
public class InfoPelis extends javax.swing.JFrame {

    private Pelicula peliculaActual;

    /**
     * Creates new form InfoPelis
     */
    public InfoPelis(Pelicula peliculaActual) {
        this.peliculaActual = peliculaActual;
        initComponents();

        lblTituloPelicula.setText(peliculaActual.getNombre());
//        lblCategoriaPelicula.setText(peliculaActual.getCategoria());
        lblLenguajePelicula.setText(peliculaActual.getLenguaje());
        lblDescripcionPelicula.setText(peliculaActual.getDescripcion());

        int calificacion = 0;
        ArrayList<Comentario> comentarios = peliculaActual.getComentario();
        if (comentarios.size() > 0) {
            for (Comentario comentario : comentarios) {
                calificacion += comentario.getCalificacion();
            }
            calificacion = calificacion / comentarios.size();
        }

        switch (calificacion) {
            case 5:
                lblCalificacionPelicula.setText("★★★★★");
                break;
            case 4:
                lblCalificacionPelicula.setText("★★★★☆");
                break;
            case 3:
                lblCalificacionPelicula.setText("★★★☆☆");
                break;
            case 2:
                lblCalificacionPelicula.setText("★★☆☆☆");
                break;
            case 1:
                lblCalificacionPelicula.setText("★☆☆☆☆");
                break;
            default:
                lblCalificacionPelicula.setText("★★★★★");
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        FotoPeli = new javax.swing.JPanel();
        btn_calificar = new javax.swing.JButton();
        OkButton = new javax.swing.JButton();
        lblComentarios = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        lblLenguaje = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblTituloPelicula = new javax.swing.JLabel();
        lblCategoriaPelicula = new javax.swing.JLabel();
        lblLenguajePelicula = new javax.swing.JLabel();
        lblDescripcionPelicula = new javax.swing.JLabel();
        lblCalificacionPelicula = new javax.swing.JLabel();
        btnComentarios = new javax.swing.JButton();

        Titulo2.setText("Duracion");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(57, 62, 70));

        jPanel1.setBackground(new java.awt.Color(57, 62, 70));

        FotoPeli.setBackground(new java.awt.Color(153, 153, 153));
        FotoPeli.setForeground(new java.awt.Color(57, 62, 70));

        javax.swing.GroupLayout FotoPeliLayout = new javax.swing.GroupLayout(FotoPeli);
        FotoPeli.setLayout(FotoPeliLayout);
        FotoPeliLayout.setHorizontalGroup(
            FotoPeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 145, Short.MAX_VALUE)
        );
        FotoPeliLayout.setVerticalGroup(
            FotoPeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 179, Short.MAX_VALUE)
        );

        btn_calificar.setBackground(new java.awt.Color(144, 55, 73));
        btn_calificar.setForeground(new java.awt.Color(255, 255, 255));
        btn_calificar.setText("Calificar");
        btn_calificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calificarActionPerformed(evt);
            }
        });

        OkButton.setBackground(new java.awt.Color(144, 55, 73));
        OkButton.setForeground(new java.awt.Color(255, 255, 255));
        OkButton.setText("Volver");
        OkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkButtonActionPerformed(evt);
            }
        });

        lblComentarios.setBackground(new java.awt.Color(255, 255, 255));
        lblComentarios.setForeground(new java.awt.Color(255, 255, 255));
        lblComentarios.setText("Calificación Promedio");

        lblDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        lblDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        lblDescripcion.setText("Descripción");

        lblLenguaje.setBackground(new java.awt.Color(255, 255, 255));
        lblLenguaje.setForeground(new java.awt.Color(255, 255, 255));
        lblLenguaje.setText("Lenguaje");

        lblCategoria.setBackground(new java.awt.Color(255, 255, 255));
        lblCategoria.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoria.setText("Categoría");

        lblTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Titulo");

        lblTituloPelicula.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloPelicula.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblTituloPelicula.setText("jLabel1");

        lblCategoriaPelicula.setBackground(new java.awt.Color(255, 255, 255));
        lblCategoriaPelicula.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblCategoriaPelicula.setText("jLabel1");

        lblLenguajePelicula.setBackground(new java.awt.Color(255, 255, 255));
        lblLenguajePelicula.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblLenguajePelicula.setText("jLabel1");

        lblDescripcionPelicula.setBackground(new java.awt.Color(255, 255, 255));
        lblDescripcionPelicula.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblDescripcionPelicula.setText("jLabel1");

        lblCalificacionPelicula.setBackground(new java.awt.Color(255, 255, 255));
        lblCalificacionPelicula.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblCalificacionPelicula.setText("jLabel1");

        btnComentarios.setBackground(new java.awt.Color(87, 86, 86));
        btnComentarios.setForeground(new java.awt.Color(255, 255, 255));
        btnComentarios.setText("Ver Comentarios");
        btnComentarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComentariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(btn_calificar)
                        .addGap(66, 66, 66)
                        .addComponent(lblDescripcionPelicula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(FotoPeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblComentarios, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLenguaje, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCalificacionPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLenguajePelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCategoriaPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 82, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTituloPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnComentarios)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(OkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(FotoPeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTituloPelicula)
                        .addGap(12, 12, 12)
                        .addComponent(lblCategoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCategoriaPelicula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblLenguaje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLenguajePelicula)
                        .addGap(16, 16, 16)
                        .addComponent(lblDescripcion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDescripcionPelicula, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                            .addComponent(btn_calificar))))
                .addGap(11, 11, 11)
                .addComponent(lblComentarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCalificacionPelicula)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnComentarios)
                    .addComponent(OkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_OkButtonActionPerformed

    private void btn_calificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calificarActionPerformed
        CalificacionPelis cal = new CalificacionPelis(peliculaActual);
        cal.setVisible(true);
    }//GEN-LAST:event_btn_calificarActionPerformed

    private void btnComentariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComentariosActionPerformed
        Comentarios test = new Comentarios(peliculaActual);
        test.setVisible(true);
    }//GEN-LAST:event_btnComentariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoPelis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoPelis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoPelis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoPelis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfoPelis(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FotoPeli;
    private javax.swing.JButton OkButton;
    private javax.swing.JLabel Titulo2;
    private javax.swing.JButton btnComentarios;
    private javax.swing.JButton btn_calificar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCalificacionPelicula;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblCategoriaPelicula;
    private javax.swing.JLabel lblComentarios;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblDescripcionPelicula;
    private javax.swing.JLabel lblLenguaje;
    private javax.swing.JLabel lblLenguajePelicula;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloPelicula;
    // End of variables declaration//GEN-END:variables
}
